In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


##Intro tensors

##Creating Tensors

In [2]:
#scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

3

In [6]:
#Vector

vector = torch.tensor([3,5])
vector

tensor([3, 5])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [11]:
#Matrix

matrix = torch.tensor([[2,3],[6,7]])
matrix

tensor([[2, 3],
        [6, 7]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix[1]

tensor([6, 7])

In [16]:
#tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,3]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [2, 5, 3]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 2, 3])

In [20]:
TENSOR.size

<function Tensor.size>